using System;
using MongoDB.Bson;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Greenergy.Emissions.API.Client.Models;

namespace Greenergy.Emissions.API.Server.Models.Mongo
{
    public class EmissionDataMongo : IComparable<EmissionDataMongo>
    {
        [MongoDB.Bson.Serialization.Attributes.BsonId]
        // standard BSonId generated by MongoDb
        public ObjectId InternalId { get; set; }

        public EmissionDataMongo(int Emission, DateTime EmissionTimeUTC, string Region)
        {
            this.Emission = Emission;
            this.EmissionTimeUTC = EmissionTimeUTC;
            this.Region = Region;
        }

        public static explicit operator EmissionDataDTO(EmissionDataMongo em)
        {
            return new EmissionDataDTO {
                Emission = em.Emission,
                EmissionTimeUTC = em.EmissionTimeUTC,
                Region = em.Region,
                RecordedTimeUTC = em.RecordedTimeUTC
            };
        }

        [Required]
        public int Emission { get; set; }
        [Required]
        public DateTime EmissionTimeUTC { get; set; }
        [Required]
        public string Region { get; set; }
        public DateTime RecordedTimeUTC { get; set; } = DateTime.UtcNow;

        public int CompareTo(EmissionDataMongo other)
        {
            return this.EmissionTimeUTC.CompareTo(other.EmissionTimeUTC);
        }
    }
}