using System;
using MongoDB.Bson;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Greenergy.API.Models;

namespace Greenergy.Models
{
    public class EmissionDataMongo : IComparable<EmissionDataMongo>
    {
        [MongoDB.Bson.Serialization.Attributes.BsonId]
        // standard BSonId generated by MongoDb
        public ObjectId InternalId { get; set; }

        public EmissionDataMongo(int Emission, DateTime TimeStampUTC, string Region)
        {
            this.Emission = Emission;
            this.TimeStampUTC = TimeStampUTC;
            this.Region = Region;
        }

        public static explicit operator EmissionDataDTO(EmissionDataMongo em)
        {
            return new EmissionDataDTO {
                Emission = em.Emission,
                TimeStampUTC = em.TimeStampUTC,
                Region = em.Region
            };
        }

        [Required]
        public int Emission { get; set; }
        [Required]
        public DateTime TimeStampUTC { get; set; }
        [Required]
        public string Region { get; set; }
        public DateTime CreatedOn { get; set; } = DateTime.Now;

        public int CompareTo(EmissionDataMongo other)
        {
            return this.TimeStampUTC.CompareTo(other.TimeStampUTC);
        }
    }
}