using System;
using MongoDB.Bson;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;

namespace Greenergy.TeslaCharger.MongoModels
{
    public class TeslaOwnerMongo
    {
        [MongoDB.Bson.Serialization.Attributes.BsonId]
        // standard BSonId generated by MongoDb
        public ObjectId InternalId { get; set; }

        public TeslaOwnerMongo(string Email)
        {
            this.Email = Email;
        }
        public TeslaOwnerMongo()
        {
        }

        [Required]
        public string Email { get; set; }
        [Required]
        public string AccessToken { get; set; }
        [Required]
        public List<TeslaVehicleMongo> vehicles;
    }
}