using System;
using MongoDB.Bson;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Greenergy.Models
{
    public class EmissionData: IComparable<EmissionData>
    {
        [MongoDB.Bson.Serialization.Attributes.BsonId]
        // standard BSonId generated by MongoDb
        public ObjectId InternalId { get; set; }

//        [Required]
        // external ID or key, which may be easier to reference (ex: 1,2,3 etc.)
//        public string Id { get; set; }

        public EmissionData (int Emission, DateTime TimeStampUTC, string Region)
        {
            this.Emission = Emission;
            this.TimeStampUTC = TimeStampUTC;
            this.Region = Region;
        }

        [Required]
        public int Emission { get; set; }
        [Required]
        public DateTime TimeStampUTC { get; set; }
        [Required]
        public string Region { get; set; }
        public DateTime CreatedOn { get; set; } = DateTime.Now;

        public int CompareTo(EmissionData other)
        {
            return this.TimeStampUTC.CompareTo(other.TimeStampUTC);
        }
    }
}