kind: Service
apiVersion: v1
metadata:
  name: emissions-chatbot-service
spec:
  selector:
    app: emissions-chatbot
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: emissions-chatbot-deployment
  labels:
    app: emissions-chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emissions-chatbot
  template:
    metadata:
      labels:
        app: emissions-chatbot
    spec:
      containers:
      - name:  greenergy-chatbot
        image: sorbra/emissions-chatbot:0.2.0
        imagePullPolicy: Always
        volumeMounts: 
        - name: "appsettings"
          mountPath: "/app/emissions-chatbot/emissions-chatbot.fulfillment/appsettings.json"
          subPath: "appsettings.json"
      volumes:
      - name: "appsettings"
        configMap: 
          name: "emissions-chatbot.appsettings"
