kind: Service
apiVersion: v1
metadata:
  name: emissions-api-service
spec:
  selector:
    app: emissions-api
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: emissions-api-deployment
  labels:
    app: emissions-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emissions-api
  template:
    metadata:
      labels:
        app: emissions-api
    spec:
      containers:
      - name:  emissions-api
        image: sorbra/emissions-api:0.2.0
        imagePullPolicy: Always
        volumeMounts: 
        - name: "appsettings"
          mountPath: "/app/emissions-api.server/appsettings.json"
          subPath: "appsettings.json"
      volumes:
      - name: "appsettings"
        configMap: 
          name: "emissions-api.appsettings"
